version: "3.9"

services:

  auth_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: innovator_user
      POSTGRES_PASSWORD: "Nep@tronix9335%"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kms_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: kms_db
      POSTGRES_USER: innovator_user
      POSTGRES_PASSWORD: "Nep@tronix9335%"
    volumes:
      - kms_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  elearning_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: elearning_db
      POSTGRES_USER: innovator_user
      POSTGRES_PASSWORD: "Nep@tronix9335%"
    volumes:
      - elearning_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  ecommerce_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: innovator_user
      POSTGRES_PASSWORD: "Nep@tronix9335%"
    volumes:
      - ecommerce_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  auth_service:
    build: ./auth_service
    restart: always
    env_file:
      - auth_service/.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=auth_service.settings.prod
    ports:
      - "8010:8000"
    command: [ "gunicorn", "auth_service.wsgi:application", "--bind", "0.0.0.0:8000", "--timeout", "120" ]
    depends_on:
      - auth_db

  kms_service:
    build: ./kms_service
    restart: always
    env_file:
      - kms_service/.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=kms_service.settings.prod
      - AUTH_SERVICE_URL=http://auth_service:8000/api/auth

    ports:
      - "8002:8002"
    command: [ "gunicorn", "kms_service.wsgi:application", "--bind", "0.0.0.0:8002", "--timeout", "120" ]
    depends_on:
      - kms_db

  elearning_service:
    build: ./elearning_service
    restart: always
    env_file:
      - elearning_service/.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=elearning_service.settings.prod
      - AUTH_SERVICE_URL=http://auth_service:8000/api/auth

    ports:
      - "8003:8003"
    command: [ "gunicorn", "elearning_service.wsgi:application", "--bind", "0.0.0.0:8003", "--timeout", "120" ]
    depends_on:
      - elearning_db

  ecommerce_service:
    build: ./ecommerce_service
    restart: always
    env_file:
      - ecommerce_service/.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=ecommerce_service.settings.prod
      - AUTH_SERVICE_URL=http://auth_service:8000/api/auth
    ports:
      - "8004:8004"
    command: [ "gunicorn", "ecommerce_service.wsgi:application", "--bind", "0.0.0.0:8004", "--timeout", "120" ]
    depends_on:
      - ecommerce_db

volumes:
  auth_db_data:
  kms_db_data:
  elearning_db_data:
  ecommerce_db_data:
