version: '3.8'

services:
  # --- AUTH SERVICE ---
  auth_db:
    image: postgres:15
    container_name: innovator-auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: innovator_user
      POSTGRES_PASSWORD: Nep@tronix9335%
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - backend_network

  auth-service:
    build: ./auth_service
    container_name: innovator-auth_service
    env_file:
      - ./auth_service/.env
    environment:
      - DJANGO_SETTINGS_MODULE=auth_service.settings.local
      - SHARED_JWT_SECRET=innovator-django-secret-key-shared-microservices-12345
    volumes:
      - ./auth_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - auth_db
    networks:
      backend_network:
        aliases:
          - auth-service

  # --- KMS SERVICE ---
  kms_db:
    image: postgres:15
    container_name: innovator-kms_db
    environment:
      POSTGRES_DB: kms_db
      POSTGRES_USER: innovator_user
      POSTGRES_PASSWORD: Nep@tronix9335%
    ports:
      - "5434:5432"
    volumes:
      - kms_data:/var/lib/postgresql/data
    networks:
      - backend_network

  kms-service:
    build: ./kms_service
    container_name: innovator-kms_service
    env_file:
      - ./kms_service/.env
    environment:
      - DJANGO_SETTINGS_MODULE=kms_service.settings.local
      - AUTH_SERVICE_URL=http://auth-service:8000/api/auth
      - SHARED_JWT_SECRET=innovator-django-secret-key-shared-microservices-12345
    volumes:
      - ./kms_service:/app
    ports:
      - "8002:8002" # internal Django port is 8000
    depends_on:
      - kms_db
      - auth-service
    networks:
      backend_network:
        aliases:
          - kms-service
          - kms-api

  # --- ELEARNING SERVICE ---
  elearning_db:
    image: postgres:15
    container_name: innovator-elearning_db
    environment:
      POSTGRES_DB: elearning_db
      POSTGRES_USER: innovator_user
      POSTGRES_PASSWORD: Nep@tronix9335%
    ports:
      - "5435:5432"
    volumes:
      - elearning_data:/var/lib/postgresql/data
    networks:
      - backend_network

  elearning-service:
    build: ./elearning_service
    container_name: innovator-elearning_service
    env_file:
      - ./elearning_service/.env
    environment:
      - DJANGO_SETTINGS_MODULE=elearning_service.settings.local
      - AUTH_SERVICE_URL=http://auth-service:8000/api/auth
      - SHARED_JWT_SECRET=innovator-django-secret-key-shared-microservices-12345
    volumes:
      - ./elearning_service:/app
    ports:
      - "8003:8003" # internal Django port 8000 or 8003 depending on runserver
    depends_on:
      - elearning_db
      - auth-service
    networks:
      backend_network:
        aliases:
          - elearning-service
          - elearning-api

  # --- Ecommerce Service ---
  ecommerce_db:
    image: postgres:15
    container_name: innovator-ecommerce_db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: innovator_user
      POSTGRES_PASSWORD: Nep@tronix9335%
    ports:
      - "5436:5432"
    volumes:
      - ecommerce_data:/var/lib/postgresql/data
    networks:
      - backend_network

  ecommerce-service:
    build: ./ecommerce_service
    container_name: innovator-ecommerce_service
    env_file:
      - ./ecommerce_service/.env
    environment:
      - DJANGO_SETTINGS_MODULE=ecommerce_service.settings.local
      - AUTH_SERVICE_URL=http://auth-service:8000/api/auth
      - SHARED_JWT_SECRET=innovator-django-secret-key-shared-microservices-12345
    volumes:
      - ./ecommerce_service:/app
    ports:
      - "8004:8004" # internal Django port 8000 or 8004 depending on runserver
    depends_on:
      - ecommerce_db
      - auth-service
    networks:
      backend_network:
        aliases:
          - ecommerce-service
          - ecommerce-api

# --- SHARED STORAGE ---
volumes:
  auth_data:
  kms_data:
  elearning_data:
  ecommerce_data:

    # --- NETWORK ---
networks:
  backend_network:
    driver: bridge
