# Generated by Django 6.0.2 on 2026-02-23 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0002_student_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCompensationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('FIXED_MONTHLY', 'Fixed Monthly'), ('HOURLY', 'Hourly Rate'), ('PER_CLASS', 'Per Class Rate')], default='FIXED_MONTHLY', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Amount per month, hour, or class', max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Commission % (e.g., 5.00 for 5%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'school')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSalarySlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_classes', models.IntegerField(default=0)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, help_text='Manual additions/deductions', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LOCKED', 'Locked'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('admin_override', models.BooleanField(default=False)),
                ('override_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'school', 'month', 'year')},
            },
        ),
    ]
