# Generated by Django 6.0.2 on 2026-03-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0003_teachercompensationrule_teachersalaryslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherkyc',
            name='kyc_status_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='teacherkyc',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherkyc',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
