# Generated by Hand to fix missing full_name

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0005_user_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
