# Generated by Django 6.0.2 on 2026-03-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0006_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherkyc',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherkyc',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherkyc',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherkyc',
            name='n_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherkyc',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/photos/'),
        ),
    ]
