# Generated by Django 6.0.2 on 2026-03-13 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0009_add_on_update_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_classes', models.IntegerField(default=0)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Commission % (e.g., 5.00)', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=13.0, help_text='Tax % (e.g., 13.00)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, help_text='Manual additions/deductions', max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, help_text='base + commission + adjustments', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, help_text='gross - tax', max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_invoices', to='kms.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='kms.teacher')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'unique_together': {('teacher', 'school', 'month', 'year')},
            },
        ),
    ]
