# Generated by Django 6.0.2 on 2026-03-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0010_teacher_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinvoice',
            name='bank_qr_code',
            field=models.URLField(blank=True, help_text='URL to the uploaded bank QR code image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
