# Generated by Django 6.0.2 on 2026-03-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0011_invoice_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinvoice',
            name='bank_qr_code',
            field=models.ImageField(blank=True, help_text='Uploaded bank QR code image', null=True, upload_to='invoice_qrs/'),
        ),
    ]
