# Generated by Django 6.0.2 on 2026-03-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0012_change_qr_to_imagefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinvoice',
            name='bank_qr_code',
        ),
    ]
