# Generated by Django 6.0.2 on 2026-03-13 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0013_remove_bank_qr_code_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.UUIDField()),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('bank_qr_code', models.ImageField(blank=True, null=True, upload_to='coordinator_invoices/qrs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
