# Generated by Django 6.0.2 on 2026-03-15 10:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0014_add_coordinator_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('Approve', 'Approved'), ('Reject', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_logs', to='kms.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_logs', to='kms.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_logs', to='kms.teacher')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['teacher', 'date'], name='kms_lessonl_teacher_3fd73e_idx'), models.Index(fields=['school', 'status'], name='kms_lessonl_school__4b5271_idx')],
            },
        ),
    ]
