# Generated by Django 6.0.2 on 2026-03-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0015_lessonlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lessonlog',
            name='kms_lessonl_teacher_3fd73e_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonlog',
            name='kms_lessonl_school__4b5271_idx',
        ),
        migrations.DeleteModel(
            name='LessonLog',
        ),
    ]
