# Generated by Django 6.0.2 on 2026-02-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='course_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
