# Generated by Django 6.0.2 on 2026-02-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_coursecontent_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='elearning.course'),
        ),
    ]
